### PR TITLE
Great Western Trail V2: Update city names on board asset

### PR DESCRIPTION
**Pull request by akwilliamson**
### What

This replaces `board.png` with a version containing updated city names. I saw in the backend repo that there's some complexity around updating the actual city names in code since there's overlap with the expansion city name variables. Also, I don't know Java 😅 so I figure just changing the asset itself does no harm to the underlying logic. The font used was "Norwester"

Linked issue from other repo: https://github.com/tomwetjens/boardgamefiesta/issues/62

### CODE REVIEW

**Comment by tomwetjens** [comment]
Hi @akwilliamson , thanks for opening a pull request!

Great idea to update the city names. Your updated image looks great. Couple of questions though, to make the change complete:
1. Could you also update the original SVG file? See newartwork/board.svg. So I can regenerate the PNG whenever changes are necessary
2. Does the mentioned font have a permissive license that allows me to use it?
3. To be consistent, the log messages also need to be updated. See the "gwt.log.values" in src/app/gwt/locale/en.json. All the JSON values (like "TOPEKA", "WICHITA") would need to be overridden in src/app/gwt2/locale/en.json by adding them there with a different value. It's a bit cheating. 

However with point 3 you see a problem arising: even if you would change the value of "SAN_FRANCISCO" to "New York" in the 2nd edition locale JSON, there is also a SAN_FRANCISCO used in the RTTN expansion so making that change would incorrectly affect the RTTN mode as well.
I see no better alternative than to just get it over with and change the Java source code to actually reflect the new city names. 
This would need to happen in this file: https://github.com/tomwetjens/boardgamefiesta/blob/113bb95757e93dfe3639f97bd700856595ea5de1/gwt/src/main/java/com/boardgamefiesta/gwt/logic/RailroadTrack.java#L168

I can take care of the Java part. If you could fix the SVG then I can merge your pull request after I have made the Java changes.

**Comment by tomwetjens** [comment]
Oh, we also need to change the names of the cattle cards... same mechanism

**Comment by akwilliamson** [comment]
Sure thing! I think I'll have some time this weekend to update this. As far as the city names in the code (again, I know nothing so disregard this if it's preposterous...) would it be easier to just prefix or suffix them with the context of the game they are in? e.g. `CHICAGO_V2` vs `CHICAGO_RTTN`?

**Comment by akwilliamson** [comment]
It looks like the `newartwork/board.svg` only displays the top corner of the board for me. Should that be the entire board? Also the license for the font should be usable - heres' the reference to the license https://www.fontsquirrel.com/license/norwester

**Comment by tomwetjens** [comment]
Yes, it should have the entire board for both the 1st and 2nd edition. I usually edit it with Inkscape.

Anyway, I changed the SVG just now: https://github.com/tomwetjens/boardgamefiesta-app/commit/f8602a14531812b1dee372ee628e1093939ad660#diff-e36b00d785184ba5a986bba16e8e5d8bcae7fc2f114ad79f88f9edd00092e637

So I can merge your PR :-)

**Comment by akwilliamson** [comment]
Yeehaw!

**Pull request merged**
